import { Inter } from 'next/font/google'
import Link from "next/link"; 
import Navbar from "../components/Header/Header"
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Projet Router',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr" suppressHydrationWarning={true}>
      <body className={inter.className }>
        <Navbar />  
        <nav className='p-5 bg-red-300 mb-10'>
            <ul className="flex justify-center gap-3">
              <li className="nav-item"><Link href="/">accueil</Link></li>
              <li className="nav-item"><Link href="/about">Qui sommes-nous</Link></li>
              <li className="nav-item"><Link href="/blog">Blog</Link></li>
              <li className="nav-item"><Link href="/create">Créer un post</Link></li>
              <li className="nav-item"><Link href="https://www.hitomba.com">Officiel</Link></li>
            </ul> 
        </nav>
        {children}
      </body>
    </html>
  )
}
